### ISSUE TITLE
Using "implementation" (As advised in the README) causes a ModResolutionException for duplicated fabricloader

### ISSUE THREAD

**Issue by ghost** [P03W/Microconfig#1]
**Microconfig Version:** 1.0.5
**Loom Version:** 0.6-SNAPSHOT
**Log:** https://hatebin.com/bolsarrubf

I suggest changing the "implementation" in the README.md to "modImplementation", as it removes any nested JARs included.

**Comment by SilverAndro** [comment]
Thanks for pointing this out
